name: Aggiorna file JSON da Google Sheets

on:
  workflow_dispatch:
    inputs: {}

jobs:
  aggiorna-json:
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v3

  
      - name: Ottieni i dati di "Libri" da Google Sheets
        uses: asibs/gsheet.action.asibs@release
        with:
          spreadsheetId: ${{ secrets.GSHEET_SPREADSHEET_ID }}
          commands: | # list of commands, specified as a valid JSON string
            [
              {
                "command": "getData",
                "args": {
                    "range": "'Libri'!A:G",
                    "hasHeaderRow": true
                }
              }
            ]
          outputFile: libri.json
        env:
              GSHEET_CLIENT_EMAIL: ${{ secrets.GSHEET_CLIENT_EMAIL }}
              GSHEET_PRIVATE_KEY: ${{ secrets.GSHEET_PRIVATE_KEY }}
        
      - name: Commit libri.json
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add libri.json
          git commit -m "Aggiorna libri.json"
          git push https://github.com/juvenestech/Libri.git
        shell: /usr/bin/bash -e {0}
