name: Aggiorna file JSON da Google Sheets

on:
  workflow_dispatch:
    inputs:
      sheets:  # This input will hold a comma-separated list of sheet names
        type: string
        default: "Libri Quinto Piano, Classici, Romanzo, Lingue, Avventura, Romanzi Rosa, Manuali, Romanzi Di Formazione"

jobs:
  aggiorna-json:
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v3

      - name: Get sheet list from workflow dispatch
        id: get_sheets
        run: |
          sheets_list=$(echo ${{ github.event.inputs.sheets }})

      - name: Loop through sheets and get data
        uses: actions/github-script@v7
        with:
          script: |
            const sheets = ${{ steps.get_sheets.outputs.sheets_list }}.split(",");
            for (const sheet of sheets) {
              const sheetName = sheet.trim();
              console.log(`Getting data for sheet: ${sheetName}`);
              const outputFile = `libri/${sheetName}.json`;
              core.setOutput('sheetName', sheetName);
              core.setOutput('outputFile', outputFile);
              await actions.getAsInput('gsheet-action'); // Call the next step
            }

      - id: gsheet-action
        name: Get data from Google Sheet
        uses: asibs/gsheet.action.asibs@release
        with:
          spreadsheetId: ${{ secrets.GSHEET_SPREADSHEET_ID }}
          commands: |-  
            [
              {
                "command": "getData",
                "args": {
                  "range": "{{ core.getInput('sheetName') }}!A:G",
                  "hasHeaderRow": true
                }
              }
            ]
          outputFile: ${{ core.getInput('outputFile') }}
        env:
          GSHEET_CLIENT_EMAIL: ${{ secrets.GSHEET_CLIENT_EMAIL }}
          GSHEET_PRIVATE_KEY: ${{ secrets.GSHEET_PRIVATE_KEY }}

      - name: Commit libri.json
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add libri/*
          git commit -m "Aggiorna libri.json"
          git push https://github.com/juvenestech/Libri.git
        shell: /usr/bin/bash -e {0}