name: Aggiorna file JSON da Google Sheets

on:
  workflow_dispatch:
    inputs: {}

jobs:
  aggiorna-json:
    runs-on: ubuntu-latest
    continue-on-error: true

    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v3
  
      - name: Ottieni i dati di "Libri Quinto Piano" da Google Sheets
        uses: asibs/gsheet.action.asibs@release
        with:
          spreadsheetId: ${{ secrets.GSHEET_SPREADSHEET_ID }}
          commands: | # list of commands, specified as a valid JSON string
            [
              {
                "command": "getData",
                "args": {
                    "range": "'Libri Quinto Piano'!A:G",
                    "hasHeaderRow": true
                }
              }
            ]
          outputFile: libri/Libri_Quinto_Piano.json
        env:
          GSHEET_CLIENT_EMAIL: ${{ secrets.GSHEET_CLIENT_EMAIL }}
          GSHEET_PRIVATE_KEY: ${{ secrets.GSHEET_PRIVATE_KEY }}
        continue-on-error: true
        
      - name: Ottieni i dati di "Classici" da Google Sheets
        uses: asibs/gsheet.action.asibs@release
        with:
          spreadsheetId: ${{ secrets.GSHEET_SPREADSHEET_ID }}
          commands: | # list of commands, specified as a valid JSON string
            [
              {
                "command": "getData",
                "args": {
                    "range": "'Classici'!A:G",
                    "hasHeaderRow": true
                }
              }
            ]
          outputFile: libri/Classici.json
        env:
          GSHEET_CLIENT_EMAIL: ${{ secrets.GSHEET_CLIENT_EMAIL }}
          GSHEET_PRIVATE_KEY: ${{ secrets.GSHEET_PRIVATE_KEY }}
        continue-on-error: true

      - name: Ottieni i dati di "Romanzo" da Google Sheets
        uses: asibs/gsheet.action.asibs@release
        with:
          spreadsheetId: ${{ secrets.GSHEET_SPREADSHEET_ID }}
          commands: | # list of commands, specified as a valid JSON string
            [
              {
                "command": "getData",
                "args": {
                "range": "'Romanzo'!A:G",
                "hasHeaderRow": true
                }
              }
            ]
          outputFile: libri/Romanzo.json
        env:
          GSHEET_CLIENT_EMAIL: ${{ secrets.GSHEET_CLIENT_EMAIL }}
          GSHEET_PRIVATE_KEY: ${{ secrets.GSHEET_PRIVATE_KEY }}
        continue-on-error: true
        
      - name: Ottieni i dati di "Lingue" da Google Sheets
        uses: asibs/gsheet.action.asibs@release
        with:
          spreadsheetId: ${{ secrets.GSHEET_SPREADSHEET_ID }}
          commands: | # list of commands, specified as a valid JSON string
            [
              {
                "command": "getData",
                "args": {
                "range": "'Lingue'!A:G",
                "hasHeaderRow": true
                }
              }
            ]
          outputFile: libri/Lingue.json
        env:
          GSHEET_CLIENT_EMAIL: ${{ secrets.GSHEET_CLIENT_EMAIL }}
          GSHEET_PRIVATE_KEY: ${{ secrets.GSHEET_PRIVATE_KEY }}
        continue-on-error: true
        
        
      - name: Ottieni i dati di "Avventura" da Google Sheets
        uses: asibs/gsheet.action.asibs@release
        with:
          spreadsheetId: ${{ secrets.GSHEET_SPREADSHEET_ID }}
          commands: | # list of commands, specified as a valid JSON string
            [
              {
                "command": "getData",
                "args": {
                "range": "'Avventura'!A:G",
                "hasHeaderRow": true
                }
              }
            ]
          outputFile: libri/Avventura.json
        env:
          GSHEET_CLIENT_EMAIL: ${{ secrets.GSHEET_CLIENT_EMAIL }}
          GSHEET_PRIVATE_KEY: ${{ secrets.GSHEET_PRIVATE_KEY }}
        continue-on-error: true
        
      - name: Ottieni i dati di "Romanzi Rosa" da Google Sheets
        uses: asibs/gsheet.action.asibs@release
        with:
          spreadsheetId: ${{ secrets.GSHEET_SPREADSHEET_ID }}
          commands: | # list of commands, specified as a valid JSON string
            [
              {
                "command": "getData",
                "args": {
                "range": "'Romanzi Rosa'!A:G",
                "hasHeaderRow": true
                }
              }
            ]
          outputFile: libri/Romanzi_Rosa.json
        env:
          GSHEET_CLIENT_EMAIL: ${{ secrets.GSHEET_CLIENT_EMAIL }}
          GSHEET_PRIVATE_KEY: ${{ secrets.GSHEET_PRIVATE_KEY }}
        continue-on-error: true
        
      - name: Ottieni i dati di "Manuali" da Google Sheets
        uses: asibs/gsheet.action.asibs@release
        with:
          spreadsheetId: ${{ secrets.GSHEET_SPREADSHEET_ID }}
          commands: | # list of commands, specified as a valid JSON string
            [
              {
                "command": "getData",
                "args": {
                "range": "'Manuali'!A:G",
                "hasHeaderRow": true
                }
              }
            ]
          outputFile: libri/Manuali.json
        env:
          GSHEET_CLIENT_EMAIL: ${{ secrets.GSHEET_CLIENT_EMAIL }}
          GSHEET_PRIVATE_KEY: ${{ secrets.GSHEET_PRIVATE_KEY }}
        continue-on-error: true
        
      - name: Ottieni i dati di "Romanzi Di Formazione" da Google Sheets
        uses: asibs/gsheet.action.asibs@release
        with:
          spreadsheetId: ${{ secrets.GSHEET_SPREADSHEET_ID }}
          commands: | # list of commands, specified as a valid JSON string
            [
              {
                "command": "getData",
                "args": {
                "range": "'Romanzi Di Formazione'!A:G",
                "hasHeaderRow": true
                }
              }
            ]
          outputFile: libri/Romanzi_Di_Formazione.json
        env:
          GSHEET_CLIENT_EMAIL: ${{ secrets.GSHEET_CLIENT_EMAIL }}
          GSHEET_PRIVATE_KEY: ${{ secrets.GSHEET_PRIVATE_KEY }}
        continue-on-error: true
        
      - name: Commit libri.json
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add libri/*
          git commit -m "Aggiorna libri.json"
          git push https://github.com/juvenestech/Libri.git
        shell: /usr/bin/bash -e {0}
